/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package content_admin;

import inc.config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LUKAS PUTRA DIANTAMA
 */
public class Data_supplier extends javax.swing.JInternalFrame {
    
    Connection conn = config.Conn();
    Statement st;
    ResultSet rs;
    
      private void tampilData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("Nama Pabrik");
        model.addColumn("Kota");
        model.addColumn("Provinsi");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        try{
            String sql = "SELECT * FROM sys_supplier";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
            int no = 0;
            while(rs.next()){
                no++;
                model.addRow(new Object []{
                    no,rs.getString("supplier_id"), rs.getString("supplier_name"),rs.getString("supplier_city"),rs.getString("supplier_province"),rs.getString("supplier_address"),rs.getString("supplier_phone"),
                });
            }
            tData.setModel(model);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    /**
     * Creates new form Data_supplier
     */
    public Data_supplier() {
        initComponents();
    }
    
    private void clearText(){
        tId.setText("");
        tNama.setText("");
        tKota.setText("");
        tProvinsi.setText("");
        tAlamat.setText("");
        tHp.setText("");
        tId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tKota = new javax.swing.JTextField();
        tProvinsi = new javax.swing.JTextField();
        tHp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextPane();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false;
            }
        };
        bCari = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Nama Supplier");

        jLabel4.setText("Kota");

        jLabel5.setText("Provinsi");

        jLabel6.setText("Alamat");

        jLabel7.setText("Nomor Telepon");

        tId.setEditable(false);

        jScrollPane1.setViewportView(tAlamat);

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "Nama", "Kota", "Provinsi", "Alamat", "Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tData);

        bCari.setText("Batal");
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCariKeyPressed(evt);
            }
        });

        jLabel8.setText("Pencarian");

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Supplier");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(113, 113, 113)
                        .addComponent(tKota, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(66, 66, 66)
                            .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(124, 124, 124)
                                .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(100, 100, 100))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel7))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bTambah)
                                        .addGap(61, 61, 61)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                    .addComponent(tProvinsi)
                                    .addComponent(tHp)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bUbah)
                                        .addGap(18, 18, 18)
                                        .addComponent(bHapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(bReset)))))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bCari)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCari)
                    .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(tHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bTambah)
                            .addComponent(bUbah)
                            .addComponent(bHapus)
                            .addComponent(bReset)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        
        String cekNama = tNama.getText();
        String cekId = tId.getText();
        String cekKota = tKota.getText();
        String cekProvinsi = tProvinsi.getText();
        String cekAlamat = tAlamat.getText();
        String cekHp = tHp.getText();
        
        if(cekNama.equals("")&&cekKota.equals("")&&cekProvinsi.equals("")&&cekAlamat.equals("")&&cekHp.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Data Terlebih Dahulu!");
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
        }else if(cekNama.equals("")){
            JOptionPane.showMessageDialog(null, "Nama Supplier Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
        }else if(cekKota.equals("")){
            JOptionPane.showMessageDialog(null, "Nama Kota Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
        }else if(cekProvinsi.equals("")){
            JOptionPane.showMessageDialog(null, "Nama Provinsi Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
        }else if(cekAlamat.equals("")){
            JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
        }else if(cekHp.equals("")){
            JOptionPane.showMessageDialog(null, "Nomor Telepon Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
        }else if(cekHp.length()>=12){
            JOptionPane.showMessageDialog(null, "Nomor Telepon Maksimal 12 Digit!");
        }else{
             try{
                String sql = "INSERT INTO sys_supplier VALUES (NULL,'"+tNama.getText()+"', '"+tKota.getText()+"', '"+tProvinsi.getText()+"', '"+tAlamat.getText()+"', '"+tHp.getText()+"')";
                st = conn.createStatement();
                st.executeUpdate(sql);


                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan!");
                clearText();
                tampilData();

             }catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Nomor Telepon Maksimal 12 Digit!");
             }
        }
         
    }//GEN-LAST:event_bTambahActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("Nama Pabrik");
        model.addColumn("Kota");
        model.addColumn("Provinsi");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        try{
            String sql = "SELECT * FROM sys_supplier WHERE supplier_name LIKE '%"+tCari.getText()+"%' OR supplier_city LIKE '%"+tCari.getText()+"%' OR supplier_province LIKE '%"+tCari.getText()+"%' OR supplier_address LIKE '%"+tCari.getText()+"%' OR supplier_phone LIKE '%"+tCari.getText()+"%'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
            int no = 0;
            while(rs.next()){
                no++;
                model.addRow(new Object []{
                    no,rs.getString("supplier_id") ,rs.getString("supplier_name"),rs.getString("supplier_city"),rs.getString("supplier_province"),rs.getString("supplier_address"),rs.getString("supplier_phone"),
                });
            }
            tData.setModel(model);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tCariKeyPressed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        // TODO add your handling code here:
              clearTextCari();
    }//GEN-LAST:event_bCariActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
          if(JOptionPane.showConfirmDialog(null, "Yakin Ingin Mereset Inputan?","Reset Data",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
              JOptionPane.showMessageDialog(null,"Berhasil Mereset Inputan!");
              clearText();
          }else{
              JOptionPane.showMessageDialog(null,"Data Inputan Batal Direset!");
          }
    }//GEN-LAST:event_bResetActionPerformed

    private void tDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDataMouseClicked
        // TODO add your handling code here:
        int baris = tData.getSelectedRow();
        tId.setText(tData.getModel().getValueAt(baris, 1).toString());
        tNama.setText(tData.getModel().getValueAt(baris, 2).toString());
        tKota.setText(tData.getModel().getValueAt(baris, 3).toString());
        tProvinsi.setText(tData.getModel().getValueAt(baris, 4).toString());
        tAlamat.setText(tData.getModel().getValueAt(baris, 5).toString());
        tHp.setText(tData.getModel().getValueAt(baris, 6).toString());
    }//GEN-LAST:event_tDataMouseClicked

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        String cekId = tId.getText();
        String cekNama = tNama.getText();
        String cekKota = tKota.getText();
        String cekProvinsi = tProvinsi.getText();
        String cekAlamat = tAlamat.getText();
        String cekHp = tHp.getText();
        
        if(cekNama.equals("")&&cekKota.equals("")&&cekProvinsi.equals("")&&cekAlamat.equals("")&&cekHp.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Data Terlebih Dahulu!");
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
        } 
        else if(cekId.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih Data Yang Ingin Diubah Terlebih Dahulu!!");
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
        }else if(cekNama.equals("")){
            JOptionPane.showMessageDialog(null, "Nama Supplier Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
        }else if(cekKota.equals("")){
            JOptionPane.showMessageDialog(null, "Nama Kota Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
        }else if(cekProvinsi.equals("")){
            JOptionPane.showMessageDialog(null, "Nama Provinsi Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
        }else if(cekAlamat.equals("")){
            JOptionPane.showMessageDialog(null, "Alamat Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
        }else if(cekHp.equals("")){
            JOptionPane.showMessageDialog(null, "Nomor Telepon Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah!");
        }else if(cekHp.length()>=12){
            JOptionPane.showMessageDialog(null, "Nomor Telepon Maksimal 12 Digit!");
        }else{
              if(JOptionPane.showConfirmDialog(null, "Anda Yakin Data Yang Anda Tambahkan Sudah Benar?","Menambahkan Data",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                try{
                   String sql = "UPDATE sys_supplier SET supplier_name ='"+tNama.getText()+"',supplier_city = '"+tKota.getText()+"', supplier_province = '"+tProvinsi.getText()+"', supplier_address = '"+tAlamat.getText()+"', supplier_phone = '"+tHp.getText()+"' WHERE supplier_id = '"+tId.getText()+"'";
                   st = conn.createStatement();
                   st.executeUpdate(sql);


                   JOptionPane.showMessageDialog(null,"Data Berhasil Diubah!");
                   clearText();
                   tampilData();

                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
              } else{
                  JOptionPane.showMessageDialog(null,"Data Batal Disimpan!");
              }
        }
           
    }//GEN-LAST:event_bUbahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        String cekId = tId.getText();
        
        if(cekId.equals("")){
            JOptionPane.showMessageDialog(null, "Pilih Data Yang Akan Dihapus Terlebih Dahulu!");
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus!");
        }else {
             if(JOptionPane.showConfirmDialog(null, "Anda Yakin Menghapus Data Ini?","Menghapus Data",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                try{
                   String sql = "DELETE FROM sys_supplier WHERE supplier_id = '"+tId.getText()+"'";
                   st = conn.createStatement();
                   st.executeUpdate(sql);


                   JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus!");
                   clearText();
                   tampilData();

                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
             }else{
                  JOptionPane.showMessageDialog(null,"Data Batal Dihapus!");
             }
        }
         
    }//GEN-LAST:event_bHapusActionPerformed

     private void clearTextCari(){
        tCari.setText("");
        tampilData();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane tAlamat;
    private javax.swing.JTextField tCari;
    private javax.swing.JTable tData;
    private javax.swing.JTextField tHp;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tKota;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tProvinsi;
    // End of variables declaration//GEN-END:variables
}
